# Generated by Django 2.0.1 on 2018-06-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('category', models.ForeignKey(on_delete='CASCADE', to='pricelist.Category')),
            ],
        ),
    ]
