# Generated by Django 2.2.6 on 2020-02-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0002_pricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='base_currency',
            field=models.CharField(choices=[('K', 'KYAT'), ('B', 'BAHT')], default='K', max_length=2),
            preserve_default=False,
        ),
    ]
