# Generated by Django 2.2.6 on 2020-02-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0003_pricelist_base_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='tags',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
