# Generated by Django 2.2.6 on 2020-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0006_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='Unit',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='pricelist.unit'),
        ),
    ]
