# Generated by Django 2.2.6 on 2020-02-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0007_pricelist_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
